# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'work.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os,random
from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import datetime
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 464)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.code = QtWidgets.QPushButton(self.centralwidget)
        self.code.setGeometry(QtCore.QRect(50, 110, 141, 61))
        self.code.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.code.setObjectName("code")
        self.music = QtWidgets.QPushButton(self.centralwidget)
        self.music.setGeometry(QtCore.QRect(50, 30, 141, 51))
        self.music.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.music.setObjectName("music")
        self.pycharm = QtWidgets.QPushButton(self.centralwidget)
        self.pycharm.setGeometry(QtCore.QRect(50, 200, 141, 61))
        self.pycharm.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.pycharm.setObjectName("pycharm")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 390, 141, 61))
        self.pushButton_4.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pyqt5 = QtWidgets.QPushButton(self.centralwidget)
        self.pyqt5.setGeometry(QtCore.QRect(50, 300, 141, 61))
        self.pyqt5.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.pyqt5.setObjectName("pyqt5")
        self.textBrowser = QtWidgets.QLineEdit(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(230, 70, 531, 321))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 40, 131, 21))
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.savebtn = QtWidgets.QPushButton(self.centralwidget)
        self.savebtn.setGeometry(QtCore.QRect(610, 400, 141, 51))
        self.savebtn.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.savebtn.setObjectName("savebtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Work"))
        self.code.setText(_translate("MainWindow", "CODE"))
        self.music.setText(_translate("MainWindow", "MUSIC"))
        self.pycharm.setText(_translate("MainWindow", "PYCHARM"))
        self.pushButton_4.setText(_translate("MainWindow", "GOOGLE"))
        self.pyqt5.setText(_translate("MainWindow", "PYQT5"))
        self.label.setText(_translate("MainWindow", "REMEMBER"))
        self.savebtn.setText(_translate("MainWindow", "SAVE"))

class Main(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui=Ui_MainWindow()
        self.ui.setupUi(self)
        self.ui.code.clicked.connect(self.code)
        self.ui.pycharm.clicked.connect(self.pycharm)
        self.ui.music.clicked.connect(self.songs)
        self.ui.pyqt5.clicked.connect(self.pyct5)
        self.ui.pushButton_4.clicked.connect(self.google)
        self.ui.savebtn.clicked.connect(lambda x:self.save(self.ui.textBrowser.text(),self.ui.textBrowser))

    def save(Self,data,btn):
        with open("data.txt","a")as f:
            f.write("\n date: "+str(datetime.now())+" ->   "+str(data))
        f.close()
        btn.setText("")
        
    def songs(self):
        a=os.listdir("F:/music/new/")
        song_name_index=random.randint(0,len(a)-1)
        os.startfile(os.path.join("F:/music/new/",a[song_name_index]))
    def code(self):
        print("code")
        os.startfile("C:\\Program Files\\Microsoft VS Code\\code.exe")
    def pycharm(self):
        os.startfile("C:\\Program Files\\JetBrains\\PyCharm Community Edition 2021.1.1\\bin\\pycharm64.exe")
    def pyct5(self):
        os.startfile("C:\\Program Files (x86)\\Qt Designer\\designer.exe")
    def google(self):
        path = "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"
        os.startfile(path)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    Main_=Main()
    Main_.show()
    sys.exit(app.exec_())
