# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'work.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 464)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.code = QtWidgets.QPushButton(self.centralwidget)
        self.code.setGeometry(QtCore.QRect(50, 110, 141, 61))
        self.code.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.code.setObjectName("code")
        self.music = QtWidgets.QPushButton(self.centralwidget)
        self.music.setGeometry(QtCore.QRect(50, 30, 141, 51))
        self.music.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.music.setObjectName("music")
        self.pycharm = QtWidgets.QPushButton(self.centralwidget)
        self.pycharm.setGeometry(QtCore.QRect(50, 200, 141, 61))
        self.pycharm.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.pycharm.setObjectName("pycharm")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 390, 141, 61))
        self.pushButton_4.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pyqt5 = QtWidgets.QPushButton(self.centralwidget)
        self.pyqt5.setGeometry(QtCore.QRect(50, 300, 141, 61))
        self.pyqt5.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.pyqt5.setObjectName("pyqt5")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(230, 70, 531, 321))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.setStyleSheet("font:75 16pt\"MS Shell Dlg 2\";");
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 40, 131, 21))
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.savebtn = QtWidgets.QPushButton(self.centralwidget)
        self.savebtn.setGeometry(QtCore.QRect(610, 400, 141, 51))
        self.savebtn.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.savebtn.setObjectName("savebtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.code.setText(_translate("MainWindow", "CODE"))
        self.music.setText(_translate("MainWindow", "MUSIC"))
        self.pycharm.setText(_translate("MainWindow", "PYCHARM"))
        self.pushButton_4.setText(_translate("MainWindow", "GOOGLE"))
        self.pyqt5.setText(_translate("MainWindow", "PYQT5"))
        self.label.setText(_translate("MainWindow", "REMEMBER"))
        self.savebtn.setText(_translate("MainWindow", "SAVE"))



class Main(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui=Ui_MainWindow()
        self.ui.setupUi(self)
        self.ui.self.pushButton_4.clicked.connect(self.startbtn)

    def startbtn(self):
        print("Click")
        import os
        path = "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"
        os.startfile(path)
        print("Click end")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    # ui.setupUi(MainWindow)
    Main_=Main()
    Main_.show()
    # MainWindow.show()
    sys.exit(app.exec_())
